### ISSUE TITLE
Can I get asm layout from execMI?

### ISSUE THREAD

**Issue by dezmound** [taskcluster/gdb-js#9]
I want get info about current running machine comands of process.
In `gdb` i can attach to process:

>$ gdb
>\> attach PID
>\> layout asm

I want to use **gdb-js** for this goal, and I write some code:
```JS
const {GDB} = require('gdb-js');
const {spawn} = require('cross-spawn');

let child = spawn('gdb', ['-i=mi']);
let gdb = new GDB(child);
let promise =  gdb.attach(5870);
promise.then(function (t) {
    let promise = gdb.execMI('-data-disassemble -s $pc -e "$pc + 20" -- 0');
    promise.then(function (s) {
        console.log(s);
    });
});
```
But I get this exception:
`{ GDBError: Error while executing "-data-disassemble -s $pc -e "$pc + 20" -- 0". No registers.
    at new GDBError (/home/dez/WebstormProjects/gdb/node_modules/gdb-js/lib/index.js:2300:107)
    at /home/dez/WebstormProjects/gdb/node_modules/gdb-js/lib/index.js:267:18
    at /home/dez/WebstormProjects/gdb/node_modules/highland/lib/index.js:1830:13
    at Stream.s._send (/home/dez/WebstormProjects/gdb/node_modules/highland/lib/index.js:1532:9)
    at Stream.write (/home/dez/WebstormProjects/gdb/node_modules/highland/lib/index.js:1633:18)
    at Stream._send (/home/dez/WebstormProjects/gdb/node_modules/highland/lib/index.js:959:26)
    at push (/home/dez/WebstormProjects/gdb/node_modules/highland/lib/index.js:1498:19)
    at /home/dez/WebstormProjects/gdb/node_modules/highland/lib/index.js:2435:17
    at Stream.s._send (/home/dez/WebstormProjects/gdb/node_modules/highland/lib/index.js:1532:9)
    at Stream.write (/home/dez/WebstormProjects/gdb/node_modules/highland/lib/index.js:1633:18)
  name: 'GDBError',
  command: '-data-disassemble -s $pc -e "$pc + 20" -- 0',
  code: NaN }
`
Could you tell me what I should do to get this information?

**Comment by baygeldin** [comment]
Sure, you can do that, but in order for this to work you need to fulfill some conditions:
1) As it's written in the docs, you need regenerator runtime to make it work (`import 'regenerator-runtime/runtime'`). I'm not sure if it's the right thing to include it as a dependency or even as a peer dependency. Probably, the correct solution would be to use [transform-runtime](https://babeljs.io/docs/plugins/transform-runtime/), but I'll look into this later.
2) `gdb.attach` uses CLI commands inside it, so you should call `gdb.init` first (e.g. `gdb.init().then(() => gdb.attach(5870))`).
3) Also, you'll probably have to run it as root, because attaching external processes to GDB requires specific permissions.

You'll get output like this:
```json
{
   "asm_insns": [
      {
         "address": "0x00007f33ee701890",
         "func-name": "__read_nocancel",
         "offset": "7",
         "inst": "cmp    $0xfffffffffffff001,%rax"
      },
      {
         "address": "0x00007f33ee701896",
         "func-name": "__read_nocancel",
         "offset": "13",
         "inst": "jae    0x7f33ee7018c9 <read+73>"
      },
      {
         "address": "0x00007f33ee701898",
         "func-name": "__read_nocancel",
         "offset": "15",
         "inst": "retq   "
      },
      {
         "address": "0x00007f33ee701899",
         "func-name": "read",
         "offset": "25",
         "inst": "sub    $0x8,%rsp"
      },
      {
         "address": "0x00007f33ee70189d",
         "func-name": "read",
         "offset": "29",
         "inst": "callq  0x7f33ee71fd70 <__libc_enable_asynccancel>"
      },
      {
         "address": "0x00007f33ee7018a2",
         "func-name": "read",
         "offset": "34",
         "inst": "mov    %rax,(%rsp)"
      }
   ]
}
```
